spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gagong?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: sky0421!

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate.format_sql: true
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect

jwt:
  secret: cXdlcXdlcXdlcXdlcXdlcXdlcXdlcXdlcXdlcXdlcXdlcXdlcXdlcXdlcXdlcXdlcXdlcXdlcXcxMzEyMzEyMzEycXdl